indexing-settings:
  user-agent: "FriendlySearch"
  referrer: "http://www.google.com"
  sites:
    - url: https://sendel.ru/
      name: Sendel.ru
    - url: https://dimonvideo.ru/
      name: Dimonvideo.ru
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://www.svetlovka.ru/
      name: Svetlovka.ru

server:
  port: 8081

spring:
  datasource:
    username: dbuser
    password: password
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE

