indexing-settings:
  user-agent: "HeliontSearchBot"
  referrer: "http://www.google.com"
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru

server:
  port: 8081

spring:
  datasource:
    username: dbuser
    password: password
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: DEBUG
    org.hibernate.tool.schema: DEBUG

